### ISSUE TITLE
Time Meridiems 

### ISSUE THREAD

**Issue by realjode** [vicariousdrama/cornychat#50]
Hi, 
This is the first time I've raised an issue on GH so please excuse me if I'm doing it all wrong.

On the home page (conrnychat.com) there is a list of scheduled events & these events have a date and time.
The times are not displaying the correct AM/PM and are showing up like this - Monday, April 8 at 2:00M GMT+1

**Comment by vicariousdrama** [comment]
Thank you. - I've got a code change in recent commit 40cc0b9d918c67e51de186c636d7a72987889f81 that should address this during next server update.
